name: Publish

on:
  workflow_run:
    workflows: ["Test"]          # Must match `name:` in test.yml
    types: [ "completed" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/YOUR_USER/YOUR_REPO:latest
            ghcr.io/YOUR_USER/YOUR_REPO:${{ github.run_number }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
