name: Test

on:
  workflow_run:
    workflows: ["Build"]         # Must match `name:` in build.yml exactly
    types: [ "completed" ]       # Run whenever 'Build' completes

jobs:
  test:
    runs-on: ubuntu-latest
    # Only proceed if the 'Build' workflow concluded successfully:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test
        run: go test -v ./...
